### ISSUE TITLE
Card not recognized

### ISSUE THREAD

**Issue by wstevens0n** [tdaede/midiori#1]
I'm having issues with this card not being recognized on my X68000 Super HD.

Anyway to troubleshoot?

**Comment by tdaede** [comment]
Version 1.x or 2.x? Did you build it yourself?

**Comment by wstevens0n** [comment]
Howdt TD,

It is a V1.1

I purchased the X68000 with the card preinstalled, but the previous owner said he never used it. He did mention it was ordered thru you.

**Comment by tdaede** [comment]
Can you run db.x, and then tell me what the following command prints:
```
mes eafa00
```

**Comment by wstevens0n** [comment]
![20190609_234955](https://user-images.githubusercontent.com/25314348/59173187-53e91580-8b11-11e9-9f88-ccf487c6264d.jpg)

**Comment by tdaede** [comment]
OK, so the card is responding normally. What game are you trying to use with it? Many require a menu setting or holding a key during start.

**Comment by wstevens0n** [comment]
I tried a few from this list
https://en.m.wikipedia.org/wiki/List_of_MT-32-compatible_computer_games

I was able to get games to recognize the module from internal to midi after cleaning the ports with some deoxit. 

I am using a sc-55mk2 and confirmed output on the module is functioning via demo mod. However it seems there is no audio being received or recognized from the midori's midi output.

What else can I do to test?

Thanks again for the help.

**Comment by tdaede** [comment]
You're using the MIDI OUT port, right (the center one)? Connected to the SC-55mk2's IN?

If games are recognizing the device it's likely a cabling issue.

**Comment by wstevens0n** [comment]
Yes it's the correct wiring like your diagram. 

I'm now wondering if it's the TRS to 5 DIN adapter cable I purchased.
Is this the correct pinout for female DIN?

3, 1 - None
5 - TX 
2 - GND
4 - VD

**Comment by tdaede** [comment]
That's the correct DIN pinout, but there are two ways to do the 3.5mm bit. Midiori uses Type A (Korg/Akai)

**Comment by wstevens0n** [comment]
Hey TD,

We are good to close the issue. I soldered DIN socket and it solved everything completely. The TRS I purchased had purchased was incorrect.

Thanks again!

**Comment by tdaede** [comment]
Great!

I'm considering switching the adapter to 2.5mm on a future version because there is only 1 common wiring for that. Or possibly only using DIN sockets.
