### ISSUE TITLE
Pinout of the 5pin miniDIN

### ISSUE THREAD

**Issue by mobiusstriptech** [tdaede/midiori#3]
Do you have a diagram or a schematic that explains the pinout for the 5pin miniDIN? I have been trying to make an adapter cable to work with a full size 5 pin DIN and have not had any luck.

**Comment by tdaede** [comment]
It is 1:1 pin numbering. It's really annoying to make as 5 pin miniDIN is pretty uncommon nowadays (I actually have some cards remaining to sell, but the annoyance of having to make a bunch of adapters has caused me to put it off...).

**Comment by mobiusstriptech** [comment]
![20220204_170523](https://user-images.githubusercontent.com/49572712/152623388-2c19e552-404a-4461-ab65-785ed9139ff2.jpg)
So this is what I used, but my SC55 doesn't seem to see a signal. I guess I need to investigate further.

**Comment by mobiusstriptech** [comment]
Do you know if this has ever been tested on a x68030? That is what I am using. When I load Castlevania it asks me which audio output to use, but no matter what midi unit I select, I get no output.

**Comment by tdaede** [comment]
Do you have a way to write disk images or transfer files? I can send you a test program to make sure the card is working.

**Comment by mobiusstriptech** [comment]
Unfortunately I don't right now. I am making the assumption that the Midiori is working at least partially. Since Castlevania asks me to choose the audio output. I should be able to test this cable with an original midi card later this week.

**Comment by tdaede** [comment]
If it detects it then it's at least working partially. I have never tested on X68030 but the test program should find most problems. FWIW pins 2, 4, and 5 are the only ones that actually matter. Did you get one that was manufactured by me or by someone else?

**Comment by mobiusstriptech** [comment]
I built it myself. I didn't see you selling them anymore but wanted to try one. I could ask a friend to write a floppy for me if that would work. One of my friends has the ability to do so.

**Comment by tdaede** [comment]
Yeah I just wanted to check if there were any construction errors we could potentially watch for as well. It would be good to run the test program to separate problems with the bus and MIDI chip emulation, and problems talking to your synth. I'll see if I can put the files in the repo.

**Comment by mobiusstriptech** [comment]
I built a new Midiori today but still am not able to get my devices working. At this point I'm assuming it's a cable or device issue. Hopefully I didn't kill the optocouplers or worse with a backwards wire.

**Comment by mobiusstriptech** [comment]
Got a new cable today and confirmed that the midi units are testing good with the built in loopback tests. I'm starting to wonder if there is an incompatibility with the x68030?

**Comment by mobiusstriptech** [comment]
I found the issue. It was definitely the cable. Can confirm that Midiori works with x68030.

**Comment by tdaede** [comment]
Great!
